version: "3.7"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sqlserver
    restart: unless-stopped
    networks:
      - rcm
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

networks:
  rcm:
    name: rcm-network

volumes:
  sqlvolume:
  