@url = http://localhost:5000/users-service

###
GET {{url}}
###
@email = asd@f1
@adminEmail = admin1@inflow.io
@password = Secret123!

### Register as the regular user
POST {{url}}/api/account/sign-up
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}


### Get user details as admin
GET {{url}}/api/users/{{userId}}

@userId = 1