@url = http://localhost:5000/users-service

###
GET {{url}}
###
@email = user24@rcm.ru
@password = Secret123!

### Register as the regular user
POST {{url}}/sign-up
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Login as the regular user
# @name sign_in
POST {{url}}/sign-in
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###
@accessToken = {{sign_in.response.body.$.accessToken}}

### Get user details as admin
@id = 1

GET {{url}}/users/{{id}}
Authorization: Bearer {{accessToken}}

### Change user state as admin
PUT {{url}}/users/{{id}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "id": {{id}}
}
