@url = http://localhost:5000/users-service

###
GET {{url}}
###
@email = absd@f11
@adminEmail = admin1@inflow.io
@password = Secret123!

### Register as the regular user
POST {{url}}/api/account/sign-up
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Login as the regular user
# @name sign_in
POST {{url}}/api/account/sign-in
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}


### Get user details as admin
GET {{url}}/api/users/{{userId}}

@userId = 1